version: '3.8'

services:

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    hostname: auth-service
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - eureka-server
      - redis

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    hostname: notification-service
    ports:
      - "8082:8082"
    networks:
      - my-network
    depends_on:
      - eureka-server
      - redis

  auth-db:
    image: postgres:latest
    container_name: auth-db
    hostname: auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
