spring:
  application:
    name: eureka-server

server:
  port: 8761  # ??????????? ???? Eureka Server

eureka:
  instance:
    hostname: localhost  # ??? IP-????? ???????
  client:
    registerWithEureka: false  # Eureka Server ??? ???? ?? ????????????
    fetchRegistry: false  # ?? ???? ????????? ?????? ????????

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # ???????? ?????????? ?????? Prometheus
